inherit_from: .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
