version: 2
jobs:
  tests:
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      # Store bundle cache
      - save_cache:
          key: bundle-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake spec

  rubocop:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec rake rubocop

  sorbet:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile" }}
      - restore_cache:
          key: sorbet-{{ checksum "Gemfile" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: SRB_YES=1 bundle exec srb rbi update > /dev/null
      - save_cache:
          key: sorbet-{{ checksum "Gemfile" }}
          paths:
            - sorbet
      - run: bundle exec srb tc --ignore vendor/

  mutant:
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - restore_cache:
          key: bundle-{{ checksum "Gemfile" }}
      - run: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run: bundle exec mutant -r entity_mapper -r ./spec/spec_helper -I lib  --use rspec --since origin/master -- 'EntityMapper*'

workflows:
  version: 2
  test_everything:
    jobs:
      - tests
      - rubocop
      - sorbet
      - mutant:
          filters:
            branches:
              ignore:
                - master
